import {
    SHOW_ADD_FAIL,
    SHOW_ADD_REQUEST,
    SHOW_ADD_SUCCESS,
    SHOW_DELETE_FAIL,
    SHOW_DELETE_REQUEST,
    SHOW_DELETE_SUCCESS,
    SHOW_GET_FAIL,
    SHOW_GET_REQUEST,
    SHOW_GET_SUCCESS,
    SHOW_UPDATE_FAIL,
    SHOW_UPDATE_REQUEST,
    SHOW_UPDATE_SUCCESS
} from '../constants/showConstant'