export const SHOW_ADD_SUCCESS = 'SHOW_ADD_SUCCESS'
export const SHOW_ADD_FAIL = 'SHOW_ADD_FAIL'
export const SHOW_ADD_REQUEST = 'SHOW_ADD_REQUEST'

export const SHOW_UPDATE_REQUEST = 'SHOW_UPDATE_REQUEST'
export const SHOW_UPDATE_SUCCESS = 'SHOW_UPDATE_SUCCESS'
export const SHOW_UPDATE_FAIL = 'SHOW_UPDATE_FAIL'

export const SHOW_DELETE_REQUEST = 'SHOW_DELETE_REQUEST'
export const SHOW_DELETE_FAIL = 'SHOW_DELETE_FAIL'
export const SHOW_DELETE_SUCCESS = 'SHOW_DELETE_SUCCESS'

export const SHOW_GET_SUCCESS = 'SHOW_GET_SUCCESS'
export const SHOW_GET_FAIL = 'SHOW_GET_FAIL'
export const SHOW_GET_REQUEST = 'SHOW_GET_REQUEST'